# Generated by Django 6.1.1 on 2026-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20),
        ),
    ]
