# Generated by Django 6.1.1 on 2026-09-05 11:35

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Cash Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cash book entries',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='CASH', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical voucher',
                'verbose_name_plural': 'historical vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='CASH', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
