# Generated by Django 6.1.1 on 2026-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
